### PR TITLE
Convert to Nan for multi node version capability

### PR DESCRIPTION
**Pull request by microadam**
Working towards a fix for #2 

This is currently incomplete. Decoding works, but I haven't managed to make Encoding work. 

Lines 128 and 129 are my attempts at making it work, but with either uncommented (only one is needed), the compiler errors. My C is not good enough to this working unfortunately. So hopefully someone will be able to finish it off, or point me in the right direction!

### CODE REVIEW

**Comment by stephank** [comment]
Oh, wow. This is great work, but I'm a bit unsure if it's worth the trouble.

This whole thing was kind of unfinished and the API it exposes is fundamentally broken. I didn't really understand the encoder when I wrote the bindings, ran into problems, and never finished it up.

**Comment by microadam** [comment]
Well, despite those few points, it does work and is being used by a few modules. So it definitely has it uses :) The main use I have for it is the decoder (which completely works with this PR on node 0.10, 0.12 and 4.1). Maybe it would be worth splitting the encoder and decoder into separate modules perhaps?

**Comment by kylewelsby** [comment]
Wow @microadam hats off :tophat:

**Comment by stephank** [comment]
I will look at this soon™, need to find some time this week.

**Comment by stephank** [comment]
Thanks for this! I made a couple of small changes and at least it's now building and running on several node versions. I still wouldn't trust the thing, though. ;)

Released 0.1.1 on npm.

**Comment by microadam** [comment]
Thanks for improving upon it and releasing it @stephank :)

**Pull request merged**
